version: "3.3"
services:

  secure-redis-cluster-7000:
    container_name: secure-redis-cluster-7000
    image: aanciaes/secure-redis:0.4-cluster
    network_mode: "host"
    environment:
      - REDIS_PORT=7000
      - SCONE_FORK=1
      - SCONE_MODE=HW
    devices:
      - /dev/isgx

  secure-redis-cluster-7001:
    container_name: secure-redis-cluster-7001
    image: aanciaes/secure-redis:0.4-cluster
    network_mode: "host"
    environment:
      - REDIS_PORT=7001
      - SCONE_FORK=1
      - SCONE_MODE=HW
    devices:
      - /dev/isgx

  secure-redis-cluster-7002:
    container_name: secure-redis-cluster-7002
    image: aanciaes/secure-redis:0.4-cluster
    network_mode: "host"
    environment:
      - REDIS_PORT=7002
      - SCONE_FORK=1
      - SCONE_MODE=HW
    devices:
      - /dev/isgx